"""
Django settings for api_gateway_settings project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+n%=@r9e!(-f3__+(j@zf$!065*#5p-i$27+kn9cx2s)5a9^!s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["user.bfcgroupsa.com"]

ADMINS = [('steeve', 'sngnetchedjeu@bfclimited.com'), ('siaka', 'ysiaka@bfclimited.com')]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    # 'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'corsheaders',

    'api_users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


    'api_gateway_settings.middleware.AppendSlashMiddleware',
    'api_gateway_settings.middleware.JWTUserMiddleware',
]

ROOT_URLCONF = 'api_gateway_settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api_gateway_settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'users_datastore',
        'USER': 'users',
        'PASSWORD': 'x5VC$4t+',
        'HOST': 'mysql',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'https://static.ikwen.com/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth model to use

AUTH_USER_MODEL = 'api_users.CustomUser'

# Allow cors 

<<<<<<< HEAD
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://berp.bfcgroupsa.com",
    "https://incident.bfcgroupsa.com",
    "https://entity.bfcgroupsa.com"
]
=======
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = ["https://berp.bfcgroupsa.com", "https://incident.bfcgroupsa.com", "https://entity.bfcgroupsa.com"]
>>>>>>> 42c87ad (Remove settings2.py)

# Configure rest_framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],
    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# Configure Simple jwt

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,  
    'BLACKLIST_AFTER_ROTATION': True,  
    'ALGORITHM': 'HS256',  
    'SIGNING_KEY': SECRET_KEY, 
    'AUTH_HEADER_TYPES': ('Bearer',),
    "TOKEN_OBTAIN_SERIALIZER": "api_gateway_settings.serializers.CustomTokenObtainPairSerializer",
}

# Configure SMTP 

#EMAIL_HOST = 'smtp.office365.com'
#EMAIL_HOST_USER = 'tsd@bfclimited.com'
#EMAIL_HOST_PASSWORD ='dpws@2023'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_TIMEOUT = 300
EMAIL_HOST = 'mail74.lwspanel.com' #'smtp.office365.com'
EMAIL_HOST_USER = 'no-reply@bfcgroupsa.com' #'tsd@bfclimited.com'
EMAIL_HOST_PASSWORD = 'gJ3*xY$UpCerV6P'  #'dpws@2025'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 300 # in seconds
DEFAULT_FROM_EMAIL = 'no-reply@bfcgroupsa.com' #'tsd@bfclimited.com'

<<<<<<< HEAD
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_PORT = 587 
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'sngnetchedjeu@bfclimited.com' 
# # EMAIL_HOST_USER = 'ngnetchedjeusteevemarley@gmail.com' 
# EMAIL_HOST_PASSWORD = 'Lamachette_&'
# DEFAULT_FROM_EMAIL = 'sngnetchedjeu@bfclimited.com'
=======
#DEFAULT_FROM_EMAIL = 'tsd@bfclimited.com'
CORS_ALLOW_HEADERS = list(default_headers) + [
    "accept-language",
    "x-payment-provider",
    "x-reference-id",
    "x-notification-url",
    "x-target-environment"
]
>>>>>>> 42c87ad (Remove settings2.py)
